### ISSUE TITLE
export weights to onnx

### ISSUE THREAD

**Issue by ghost** [stqc/AttentionGAN_JupyterNB#1]
can the weights to exported to onnx

**Comment by stqc** [comment]
> can the weights to exported to onnx

Yes the weights can be exported to onnx.

**Comment by ghost** [comment]
@stqc can you help with that?

**Comment by stqc** [comment]
> @stqc can you help with that?

you can find tutorial to do so on the official pytorch website!

**Comment by stqc** [comment]
Closing this issue if you have any other queries please open a new one
